### ISSUE TITLE
Mysql/MariaDb support?

### ISSUE THREAD

**Issue by michaelbukachi** [schireson/pytest-mock-resources#93]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add mysql/mariadb integration

**Describe alternatives you've considered**
None at the moment

**Additional context**
Is this currently being worked on? If not, I'd like to take it up.

**Comment by oakhan3** [comment]
Hey @michaelbukachi this is currently not in the works and we would be thrilled if you took it on!

**Comment by michaelbukachi** [comment]
Awesome. So are we going with mariadb or mysql? Also, any specific versions in mind?

**Comment by oakhan3** [comment]
I would say MySQL as it is still more prevalent than MariaDB.

But with that being said, I don't see why MariaDB can't come soon after - MySQL and MariaDB are fairly similar so implementation here won't vary much either.

You can't go wrong either way - feel free to do MariaDB first if its your primary usecase!

**Comment by michaelbukachi** [comment]
Noted. What about the version? I noticed for postgres we are using version `9.6`

**Comment by DanCardin** [comment]
I'd suggest either the most current version version, or the version you happen to be using (which is why 9.6 is the version we started on)

I have a plan (https://github.com/schireson/pytest-mock-resources/issues/79) for making the version configurable (because one should be testing with the version you use in production), so i think it will hopefully be less important what the default version is
